name: 5-roll-alert

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # lets it update .state.json
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run monitor
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python monitor.py

      - name: Test Discord Webhook
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"✅ GitHub Actions test message\"}" \
               ${{ secrets.WEBHOOK_URL }}

      - name: Commit state (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .state.json || true
          git commit -m "Update drought state" || echo "No changes"
          git push || echo "No push"
